### ISSUE TITLE
Failed to start using Distrobox + Podman

### ISSUE THREAD

**Issue by Bad3r** [RebornOS-Developers/rebornos-docker#2]
Have you tried to deploy this image using [Distrobox](https://github.com/89luca89/distrobox)? I recently learned about Distrobox and tried to start this image with it, but it failed. Here is the error log:
```py
+ [ exited != running ]
+ printf \033[31m Error: could not start entrypoint.\n\033[0m
 Error: could not start entrypoint.
+ podman --log-level debug logs --since 2022-11-25T21:43:47.956851524-05:00 RebornOS
INFO[0000] podman filtering at log level debug          
DEBU[0000] Called logs.PersistentPreRunE(podman --log-level debug logs --since 2022-11-25T21:43:47.956851524-05:00 RebornOS) 
DEBU[0000] Merged system config "/usr/share/containers/containers.conf" 
DEBU[0000] Merged system config "/etc/containers/containers.conf" 
DEBU[0000] Using conmon: "/usr/bin/conmon"              
DEBU[0000] Initializing boltdb state at /home/chell/.local/share/containers/storage/libpod/bolt_state.db 
DEBU[0000] Using graph driver overlay                   
DEBU[0000] Using graph root /home/chell/.local/share/containers/storage 
DEBU[0000] Using run root /run/user/1000/containers     
DEBU[0000] Using static dir /home/chell/.local/share/containers/storage/libpod 
DEBU[0000] Using tmp dir /run/user/1000/libpod/tmp      
DEBU[0000] Using volume path /home/chell/.local/share/containers/storage/volumes 
DEBU[0000] Set libpod namespace to ""                   
DEBU[0000] [graphdriver] trying provided driver "overlay" 
DEBU[0000] Cached value indicated that overlay is supported 
DEBU[0000] Cached value indicated that overlay is supported 
DEBU[0000] Cached value indicated that metacopy is not being used 
DEBU[0000] Cached value indicated that native-diff is usable 
DEBU[0000] backingFs=extfs, projectQuotaSupported=false, useNativeDiff=true, usingMetacopy=false 
DEBU[0000] Initializing event backend journald          
DEBU[0000] Configured OCI runtime runj initialization failed: no valid executable found for OCI runtime runj: invalid argument 
DEBU[0000] Configured OCI runtime kata initialization failed: no valid executable found for OCI runtime kata: invalid argument 
DEBU[0000] Configured OCI runtime runsc initialization failed: no valid executable found for OCI runtime runsc: invalid argument 
DEBU[0000] Configured OCI runtime krun initialization failed: no valid executable found for OCI runtime krun: invalid argument 
DEBU[0000] Using OCI runtime "/usr/bin/crun"            
INFO[0000] Setting parallel job count to 37             
DEBU[0000] Called logs.PersistentPostRunE(podman --log-level debug logs --since 2022-11-25T21:43:47.956851524-05:00 RebornOS) 
+ container_manager_log=
+ printf %s\n 

+ exit 1
+ [ 1 -ne 0 ]
+ printf \nAn error occurred\n
```

I was able to get the image to start using a docker run command, so I am not sure if this is an issue related to this image or Distrobox.

Command used to create the image:
```sh
$ distrobox-create --image rebornos/rebornos:latest --name RebornOS --home ~/distrobox/RebornOS --yes -v
```
command used to run the image
```sh
$ distrobox enter RebornOS
```

**Comment by SoulHarsh007** [comment]
Hello, Thanks for reporting this issue. I think the issue is due to the `ENTRYPOINT` directive we have configured in the Dockerfile, I think we should be using `CMD ["/usr/bin/bash"]`
I'll test it once with the changes.

**Comment by pvshvp-oss** [comment]
Hi @Bad3r ,

You may try again now with an extra argument to *distrobox-create* : `--pre-init-hooks "sh /usr/bin/init-rebornos-docker.sh"`

```sh
distrobox-create --image rebornos/rebornos:latest --name RebornOS --home ~/distrobox/RebornOS --yes -v --pre-init-hooks "sh /usr/bin/init-rebornos-docker.sh"

distrobox enter RebornOS
```

Let me know if this works for you.

That being said, the project is still relatively new, so expect bugs that we have not encountered.

**Comment by pvshvp-oss** [comment]
Hi @Bad3r, does my previous message resolve your issue?

> You may try again now with an extra argument to _distrobox-create_ : `--pre-init-hooks "sh /usr/bin/init-rebornos-docker.sh"`
> 
> ```shell
> distrobox-create --image rebornos/rebornos:latest --name RebornOS --home ~/distrobox/RebornOS --yes -v --pre-init-hooks "sh /usr/bin/init-rebornos-docker.sh"
> 
> distrobox enter RebornOS
> ```
> 
> Let me know if this works for you.
> 
> That being said, the project is still relatively new, so expect bugs that we have not encountered.

**Comment by Bad3r** [comment]
@shivanandvp sorry for the delay. I am still getting a similar error but haven't had a chance to dig deeper  
\`\`\`py  
DEBU\[0000\] Called inspect.PersistentPostRunE(podman --log-level debug inspect --type container RebornOS --format {{.State.Status}})   
\+ \[ stopped != running \]  
\+ printf \\033\[31m Error: could not start entrypoint.\\n\\033\[0m  
Error: could not start entrypoint.  
\+ podman --log-level debug logs --since 2022-12-01T09:24:33.019049544-05:00 RebornOS  
INFO\[0000\] podman filtering at log level debug            
DEBU\[0000\] Called logs.PersistentPreRunE(podman --log-level debug logs --since 2022-12-01T09:24:33.019049544-05:00 RebornOS)   
DEBU\[0000\] Merged system config "/usr/share/containers/containers.conf"   
DEBU\[0000\] Merged system config "/etc/containers/containers.conf"   
DEBU\[0000\] Using conmon: "/usr/bin/conmon"                
DEBU\[0000\] Initializing boltdb state at /home/chell/.local/share/containers/storage/libpod/bolt\_state.db   
DEBU\[0000\] Using graph driver overlay                     
DEBU\[0000\] Using graph root /home/chell/.local/share/containers/storage   
DEBU\[0000\] Using run root /run/user/1000/containers       
DEBU\[0000\] Using static dir /home/chell/.local/share/containers/storage/libpod   
DEBU\[0000\] Using tmp dir /run/user/1000/libpod/tmp        
DEBU\[0000\] Using volume path /home/chell/.local/share/containers/storage/volumes   
DEBU\[0000\] Set libpod namespace to ""                     
DEBU\[0000\] \[graphdriver\] trying provided driver "overlay"   
DEBU\[0000\] Cached value indicated that overlay is supported   
DEBU\[0000\] Cached value indicated that overlay is supported   
DEBU\[0000\] Cached value indicated that metacopy is not being used   
DEBU\[0000\] Cached value indicated that native-diff is usable   
DEBU\[0000\] backingFs=extfs, projectQuotaSupported=false, useNativeDiff=true, usingMetacopy=false   
DEBU\[0000\] Initializing event backend journald            
DEBU\[0000\] Configured OCI runtime runj initialization failed: no valid executable found for OCI runtime runj: invalid argument   
DEBU\[0000\] Configured OCI runtime kata initialization failed: no valid executable found for OCI runtime kata: invalid argument   
DEBU\[0000\] Configured OCI runtime runsc initialization failed: no valid executable found for OCI runtime runsc: invalid argument   
DEBU\[0000\] Configured OCI runtime krun initialization failed: no valid executable found for OCI runtime krun: invalid argument   
DEBU\[0000\] Using OCI runtime "/usr/bin/crun"              
INFO\[0000\] Setting parallel job count to 37               
DEBU\[0000\] Called logs.PersistentPostRunE(podman --log-level debug logs --since 2022-12-01T09:24:33.019049544-05:00 RebornOS)   
DEBU\[0000\] \[graphdriver\] trying provided driver "overlay"   
DEBU\[0000\] Cached value indicated that overlay is supported   
DEBU\[0000\] Cached value indicated that overlay is supported   
DEBU\[0000\] Cached value indicated that metacopy is not being used   
DEBU\[0000\] backingFs=extfs, projectQuotaSupported=false, useNativeDiff=true, usingMetacopy=false   
\+ container\_manager\_log=  
\+ printf %s\\n

\+ exit 1  
\+ \[ 1 -ne 0 \]  
\+ printf \\nAn error occurred\\n

An error occurred  
\+ rm -f /home/chell/.cache/.\*.fifo /home/chell/.cache/.\*.status

An error occurred  
\`\`\`

**Comment by pvshvp-oss** [comment]
1. Did you run the above 2 commands I pasted? That way we know if this issue is reproducible or not
> ```shell
> distrobox-create --image rebornos/rebornos:latest --name RebornOS --home ~/distrobox/RebornOS --yes -v --pre-init-hooks "sh /usr/bin/init-rebornos-docker.sh"
> 
> distrobox enter RebornOS
> ```

2. Did you update the docker image with `docker pull`?

I am consistently able to set up distrobox with this docker image using the above 2 commands

**Comment by Bad3r** [comment]
@shivanandvp ! Sorry for the delay, didn't get a chance to test till now. Thank you for your help!

**Comment by Bad3r** [comment]
yes I was able to start it using the command provided
